return {
	"theprimeagen/harpoon",
	config = function()
		local mark = require("harpoon.mark")
		local ui = require("harpoon.ui")

		vim.keymap.set("n", "<leader>a", mark.add_file)
		vim.keymap.set("n", "<leader>e", ui.toggle_quick_menu)
		vim.keymap.set("n", "<leader>dd", function()
			mark.clear_all()
		end)
		vim.keymap.set("n", "<leader>ah", function()
			mark.add_file()
			mark.set_current_at(1)
		end)
		vim.keymap.set("n", "<leader>aj", function()
			mark.add_file()
			mark.set_current_at(2)
		end)
		vim.keymap.set("n", "<leader>ak", function()
			mark.add_file()
			mark.set_current_at(3)
		end)
		vim.keymap.set("n", "<leader>al", function()
			mark.add_file()
			mark.set_current_at(4)
		end)
		vim.keymap.set("n", "<leader>a;", function()
			mark.add_file()
			mark.set_current_at(5)
		end)
		vim.keymap.set("n", "<leader>h", function()
			ui.nav_file(1)
		end)
		vim.keymap.set("n", "<leader>j", function()
			ui.nav_file(2)
		end)
		vim.keymap.set("n", "<leader>k", function()
			ui.nav_file(3)
		end)
		vim.keymap.set("n", "<leader>l", function()
			ui.nav_file(4)
		end)
		vim.keymap.set("n", "<leader>;", function()
			ui.nav_file(5)
		end)
		-- vim.keymap.set("n", "bn", function()
		-- 	ui.nav_next()
		-- end)
		-- vim.keymap.set("n", "bp", function()
		-- 	ui.nav_prev()
		-- end)
	end,
}
