# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/sriram/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/sriram/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/sriram/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/sriram/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

function ff() {
    aerospace list-windows --all | fzf --bind 'enter:execute(bash -c "aerospace focus --window-id {1}")+abort';
}

export XDG_CONFIG_HOME=~/.config
set -o vi

. "$HOME/.cargo/env"

eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(starship init bash)"


# # if running bash
# if [ -n "$BASH_VERSION" ]; then
#     # include .bashrc if it exists
#     if [ -f "$XDG_CONFIG_HOME/bash/bashrc" ]; then
#     . "$XDG_CONFIG_HOME/bash/bashrc"
#     fi
# fi
 eval "$(fzf --bash)"

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

source ~/.config/lf/lfcd
alias lf=~/.local/bin/lfub

# My Aliases
alias c=clear
alias fman="compgen -c | fzf | xargs man"
alias vim=nvim
alias v=nvim
alias gvim=nvim
alias xargs=gxargs
alias wgl="pbpaste | xargs wget"
alias ctags="/opt/homebrew/Cellar/ctags/5.8_2/bin/ctags -R ."

export PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"
